###############################################################
#                   Authelia configuration                    #
###############################################################

default_redirection_url: https://ozeliurs.com

server:
  address: 'tcp://:9091'

log:
  level: debug

totp:
  issuer: authelia.com

authentication_backend:
  file:
    path: /config/users_database.yml

access_control:
  default_policy: one_factor
  rules:
    - domain: traefik.ozeliurs.com
      policy: two_factor
      subject:
        groups:
          - admins

session:
  domain: ozeliurs.com

regulation:
  max_retries: 3
  find_time: 120
  ban_time: 300

storage:
  local:
    path: /config/db.sqlite3

notifier:
  filesystem:
    filename: /config/notification.txt
  smtp:
    username: notify@ozeliurs.com
    host: smtp.mail.me.com
    port: 587
    sender: notify@ozeliurs.com