###############################################################
#                   Authelia configuration                    #
###############################################################

default_redirection_url: https://ozeliurs.com

server:
  host: 0.0.0.0
  port: 9091

log:
  level: debug

totp:
  issuer: authelia.com

authentication_backend:
  file:
    path: /config/users_database.yml

access_control:
  default_policy: one_factor
  rules:
    - domain: traefik.ozeliurs.com
      policy: two_factor
      subject:
        - "group:admins"

session:
  domain: ozeliurs.com

regulation:
  max_retries: 3
  find_time: 120
  ban_time: 300

storage:
  local:
    path: /config/db.sqlite3

notifier:
  smtp:
    host: in-v3.mailjet.com
    port: 587
    sender: authelia@ozeliurs.com
    username: de381576caab290d3870433daa7372a8
